#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail   # preserve exit code when piping e.g. with "tee"

START_PATH=${PWD}
MY_NAME=`basename $0`
START_TIME_SECONDS=$SECONDS

function usage()
{
    echo  "+----------------------------------------------------------------------+"
    echo  "| ${MY_NAME} - build packer image                                      |"
    echo  "+----------------------------------------------------------------------+"
    echo  ""
    echo  "Usage: "
    echo  ""
    echo  "    -debug                     : Enable debug"
    echo  ""
    exit 1
}
function err()
{
  echo  "ERROR: occured in $(basename $0)"
  cd "${START_PATH}"
  exit 1
}

ARG_DEBUG=
ARGS=$*
while (( "$#" )); do
	ARG_RECOGNISED=FALSE

	if [ "$1" == "-h" ] ; then
		usage
	fi
	if [ "$1" == "-debug" ]; then
		ARG_DEBUG=-debug
		ARG_RECOGNISED=TRUE
	fi
	if [ "${ARG_RECOGNISED}" == "FALSE" ]; then
		echo "Invalid args : Unknown argument \"${1}\"."
		err 1
	fi
	shift
done

# Clean our vbox image output directory
[ -d ./output ] && rm -rf ./output

# Create a temporary placeholder file kickstart-cdrom/ks.cfg to prevent 'packer validate' from erroring
# kickstart-cdrom/ks.cfg will be generated by Packer from template file 'centos-kickstart.cfg.tpl'
[ -f kickstart-cdrom/ks.cfg ] && rm -f kickstart-cdrom/ks.cfg
touch kickstart-cdrom/ks.cfg

echo -e "\nValidate the Packer file..."
packer validate packer.pkr.hcl

echo -e "\nBuilding with Packer..."
packer build ${ARG_DEBUG} -on-error=ask packer.pkr.hcl 2>&1 | tee packer.log

ELAPSED_SECONDS=$(($SECONDS - START_TIME_SECONDS))
echo "$(date +'%Y%m%d %H:%M:%S') : Completed in $((ELAPSED_SECONDS/60)) min $((ELAPSED_SECONDS%60)) sec"

